### ISSUE TITLE
Error inflating class com.dx.dxloadingbutton.widget.LoadingButton

### ISSUE THREAD

**Issue by m-irfan** [StevenDXC/DxLoadingButton#7]
I am getting this error can anyone help me what I am missing or doing wrong?

This is my error log:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zapro.itradevehicle, PID: 1651
                  android.view.InflateException: Binary XML file line #149: Error inflating class com.dx.dxloadingbutton.widget.LoadingButton
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.zapro.itradevehicle.Buyer.SearchFragment.onCreateView(SearchFragment.java:85)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dx.dxloadingbutton.widget.LoadingButton" on path: DexPathList[[zip file "/data/app/com.zapro.itradevehicle-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zapro.itradevehicle-2, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.zapro.itradevehicle.Buyer.SearchFragment.onCreateView(SearchFragment.java:85) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136) 
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
Application terminated.

Thanks

**Comment by robinryden** [comment]
Same error here..

**Comment by StevenDXC** [comment]
I have updated the package name, the new package is com.dx.dxloadingbutton.lib.LoadingButton,fix it in your layout.xml. reference demo app.

**Comment by m-irfan** [comment]
Thanks StevenDXC, I haven't tried your suggestion yet but I think it will work, I had imported LoadingButton class directly to my package to temporarily fix that issue and it worked. I'll modify it as you suggested soon. Thanks for your help. You have done an excellent work 👍

**Comment by SophiaSonam** [comment]
Hi,
I am using com.dx.dxloadingbutton.lib.LoadingButton but getting error
Binary XML file line #46: Binary XML file line #46: Error inflating class com.dx.dxloadingbutton.lib.LoadingButton
Can you please help?

**Comment by m-irfan** [comment]
> Hi,
> I am using com.dx.dxloadingbutton.lib.LoadingButton but getting error
> Binary XML file line #46: Binary XML file line #46: Error inflating class com.dx.dxloadingbutton.lib.LoadingButton
> Can you please help?

@SophiaSonam 
I don't remember exact solution, but I think you just need to copy that class from library into your package. and then use it in xml. I hope this help

**Comment by mobioptions-fadma** [comment]
@SophiaSonam have you fixed the problem? I have the same issue
